package main.tracer;

import java.io.File;
import java.io.IOException;

import main.Main;
import main.load.JarData;
import main.load.JarLoader;
import main.tracer.ExecutionData;
import main.ui.JarFileChooser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.ExecutionException;
import java.util.jar.Attributes.Name;

import jdk.internal.org.objectweb.asm.tree.IntInsnNode;

public class TraceLauncher {

	private String jarPath;
	private List<ExecutionData> executions = new ArrayList<ExecutionData>(Arrays.asList(new ExecutionData()));

	public TraceLauncher(String JarPathName){
		this.jarPath = JarPathName;
	}

	/**
	 * Runs the jar file and generates and returns the traces specified by the jarPath
	 *
	 * @return The traces generated by the jar
	 * */
	public Trace[] run(){
		if(jarPath == null)return null;

		//The file of the jar to trace
		File file = new File(jarPath);

		//loads in the jar file
		JarData jd = JarLoader.loadJarFile(file);


		//the path of the jar file
		jarPath = jd.getFile().getAbsolutePath();

		final ExecutionData[] executionsArray = executions.toArray(new ExecutionData[executions.size()]);


		//grabs the jar file main class
		//grabs the main class of the jar file
		final String mainClass = jd.getManifest().getMainAttributes().getValue(Name.MAIN_CLASS);

		//grabs the classes from the jar file
		final Set<String> loadedClasses = new HashSet<String>();
		for (Class<?> cl : jd.getClasses()){
			loadedClasses.add(cl.getName());
		}

		TestThread thread = new TestThread(loadedClasses, executionsArray, mainClass);

		thread.setName("MainWindow tracer thread");
		thread.setDaemon(true);
		thread.start();

		//returns the generated traces
		return thread.getTraces();
	}


	private class TestThread extends Thread{

		// fields
		private Set<String> loadedClasses;
		private ExecutionData[] executionsArray;
		private String mainClass;


		private Trace[] traces;

		public TestThread(Set<String> loadedClasses, ExecutionData[] executionsArray, String mainClass){
			this.loadedClasses = loadedClasses;
			this.executionsArray = executionsArray;
			this.mainClass = mainClass;
		}

		@Override
		public void start(){
			run();
		}

		@Override
		public void run() {

			//Creates a filter that filters class names from the jar
			TraceFilter initialFilter = new TraceFilter() {
				@Override
				public boolean isMethodTraced(MethodKey m) {
					return loadedClasses.contains(m.className);
				}

				@Override
				public boolean isFieldTraced(FieldKey f) {
					return loadedClasses.contains(f.className);
				}

				@Override
				public boolean isParameterTraced(ParameterKey p) {
					return true;
				}
			};

			if(Main.getFilter() != null){
				System.out.println("Main Filter");
				initialFilter = Main.getFilter();
			}
			else{
				System.out.println("No main filter");
			}



			traces = new Trace[executionsArray.length];



			for (int k = 0; k < executions.size(); k++) {
				ExecutionData ed = executions.get(k);
				FutureTraceConsumer future = new FutureTraceConsumer();
				try {
					Tracer.launchAndTraceAsync("-cp \"" + jarPath + "\"",
							mainClass + " " + ed.commandLineArguments,
							initialFilter, future);
				} catch (Exception e) {
					e.printStackTrace();
				}

				try {
					traces[k] = future.get();
				} catch (InterruptedException | ExecutionException e) {
					e.printStackTrace();
				}
			}
		}

		public Trace[] getTraces(){return this.traces;}
	}

	public static void main(String[] args){

		//the jar to load the generate the trace off
		File file = new File("data/tests/TestProgram2.jar");

		//loads the jar
		JarData jarData = JarLoader.loadJarFile(file);

		//sets the path of the jar in the tracer
		TraceLauncher tracer = new TraceLauncher(jarData.getFile().getAbsolutePath());

		//start the tracer and get the traces
		Trace[] tr = tracer.run();

		//pass the traces to the trace manager
		TraceManager trm = new TraceManager(tr);

		//pass the traces to the string util
		TraceStringUtil tu = new TraceStringUtil(tr);

		//create a new filter selector
		TraceFilterSelector trs = new TraceFilterSelector();


		List<String> methodTofilter = new ArrayList<>();

		methodTofilter.add("bob");

		trs.addMethodsToFilter(methodTofilter);

		trm.applyFilter(trs.getFilter());

		TraceManager manager = new TraceManager(tr);
	}
}
